# Application Configuration
server:
  port: 8093

# Spring
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping_service?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

#spring:
#  application:
#    name: shopping-service
#  cloud:
#    config:
#      uri: http://localhost:8081
#      username: root
#      password: s3cr3t

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

Feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
