# Application Configuration
server:
  port: 8093

# Spring
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping_service?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

#spring:
#  application:
#    name: shopping-service
#  cloud:
#    config:
#      uri: http://localhost:8081
#      username: root
#      password: s3cr3t

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

Feign:
  hystrix:
   threadpool.default.coreSize: 20
   threadpool.default.maxQueueSize: 500000
   threadpool.default.keepAliveTimeMinutes: 2
   threadpool.default.queueSizeRejectionThreshold: 500000
   command:
    default:
     fallback.isolation.semaphore.maxConcurrentRequests: 20
     execution:
      timeout:
       enabled: false
      isolation:
       strategy: THREAD
       thread:
        timeoutInMilliseconds: 30000
  client:
    config:
      default:
        connectTimeout: 90000000
        readTimeout: 90000000
        
ribbon:
  ReadTimeout: 90000
  ConnectTimeout: 90000 
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 3
  clientName:
   ribbon:
     MaxAutoRetries: 5
     MaxAutoRetriesNextServer: 3
     OkToRetryOnAllOperations: true
     ReadTimeout: 90000
     ConnectTimeout: 90000 

       
management:
  endpoints:
    web:
      exposure:
        include: "*"
